package frc.robot.util;

public enum RobotState {
  IDLE,
  INTAKE_CORAL,
  HAS_PIECE_ALGAE,
  HAS_PIECE_CORAL,
  NO_PIECE_CORAL,
  NO_PIECE_ALGAE,
  SCORE_L1,
  SCORE_L2,
  SCORE_L3,
  SCORE_L4,
  MANUAL_L4,
  MANUAL_L3,
  MANUAL_L2,
  MANUAL_L1,
  INTAKE_ALGAE_FROM_REEF,
  INTAKE_ALGAE_FROM_GROUND,
  INTAKE_ALGAE_FROM_LOLIPOP,
  SCORE_ALGAE_NET,
  SCORE_ALGAE_PROCESSOR,
  CLIMB
}
