package frc.robot.util;

public enum RobotState {
  IDLE,
  INTAKE_CORAL,
  HAS_PIECE_ALGAE,
  HAS_PIECE_CORAL,
  NO_PIECE_CORAL,
  NO_PIECE_ALGAE,
  FIRE,
  // SCORE_L1,
  SCORE_L2,
  SCORE_L3,
  SCORE_L4,
  MANUAL_L4,
  MANUAL_L3,
  MANUAL_L2,
  MANUAL_L1,
  INTAKE_ALGAE_REEF_L2,
  INTAKE_ALGAE_REEF_L3,
  INTAKE_ALGAE_GROUND,
  INTAKE_ALGAE_LOLIPOP,
  ALGAE_NET,
  ALGAE_PROCESSOR,
  CLIMB
}
